### ISSUE TITLE
Link Missing

### ISSUE THREAD

**Issue by Rahul-Sridhar** [facebookresearch/d2go#10]
Hi,

Thanks for the great work! The link in the below image is missing. Could you please add the link?

![image](https://user-images.githubusercontent.com/24386877/110193689-06d7c780-7dfb-11eb-816a-dec643c2e60f.png)

**Comment by zhanghang1989** [comment]
Thanks for pointing out! The link should be https://github.com/facebookresearch/d2go/tree/master/demo#quantization-aware-training
