### ISSUE TITLE
 data augmentation

### ISSUE THREAD

**Issue by maheshs11** [facebookresearch/d2go#100]
can you please implement data augmentation  technique which is available for dectectron2 ?
as sometime training images are less in number.

#from detectron2 config file
`True` if cropping is used for data augmentation during training
_C.INPUT.CROP = CN({"ENABLED": False})
Cropping type. See documentation of `detectron2.data.transforms.RandomCrop` for explanation.
_C.INPUT.CROP.TYPE = "relative_range"
 Size of crop in range (0, 1] if CROP.TYPE is "relative" or "relative_range" and in number of
 pixels if CROP.TYPE is "absolute"
_C.INPUT.CROP.SIZE = [0.9, 0.9]

**Comment by wat3rBro** [comment]
@maheshs11 D2Go is built on top of D2, so the included data augmentation in D2 is also available in D2Go.
