### ISSUE TITLE
Latency Benchmark

### ISSUE THREAD

**Issue by Yuxin-CV** [facebookresearch/d2go#11]
Hi, thanks for your great work!

I wonder how to measure and benchmark the `Model Latency` in the model zoo on mobile devices.
Would you provide benchmark tools like `TensorFlow Lite Benchmark Tools` in the future?

Thanks.

**Comment by zhanghang1989** [comment]
Thanks for your interest. The latency is measured using internal service, which may not be able to become public.

**Comment by Yuxin-CV** [comment]
> Thanks for your interest. The latency is measured using internal service, which may not be able to become public.

Thanks for your prompt response.

**Comment by omair-kg** [comment]
@zhanghang1989 Could you provide latency benchmark values for key point estimation please.
