### ISSUE TITLE
Training time  is huge

### ISSUE THREAD

**Issue by AhmedHessuin** [facebookresearch/d2go#114]
the model training time is very very huge, the training iteration itself is fast, however the training load the whole data while training unlike detectron2, the time i needed to train model in detectron2 was 3 days for 300 000 iterations, now i need 3 days for 50 000 iterations.
while training i see the script load the whole training data all again and again which consume time.
can i speed up the training process? 
thanks in advance.

**Comment by wat3rBro** [comment]
@AhmedHessuin could you further describe "load the whole training data all again and again", have you seen any error messages? (D2Go might keep retrying loading the data)

**Comment by AhmedHessuin** [comment]
@wat3rBro  the data loading function is called over and over to load the data. 
for example i have 300 000 image in 4 folders the custom data loading function open each folder and load the training data from it 
while training:
i see the data loading function process again, and again, which mean it load the whole data like the start of the training,
no error message seen except some images contain no text file and i am handling it in my data loading function.

**Comment by AhmedHessuin** [comment]
@wat3rBro 
 ```DatasetCatalog.register("data_" + name, lambda d=d: get_docs_dicts(data_dir+"/" + d))```
get_docs_dicts

**Comment by wat3rBro** [comment]
`get_docs_dicts` should only been called once when creating the data loader, is it possible that the data loader is created many many times?

**Comment by AhmedHessuin** [comment]
i believe it's getting calls many many time.
i don't know why.

**Comment by AhmedHessuin** [comment]
@wat3rBro 
sample of my script
```
print("generate_data")
balloon_metadata,dataset_dicts=get_data_ready_id()
# print("visualize data")
# visualize(dataset_dicts)
print("train")
cfg,runner,pytorch_model=train_id()
```

```
def train_id():
    cfg, runner = prepare_for_launch_id()
    print(cfg)
    model = runner.build_model(cfg)
    runner.do_train(cfg, model, resume=False)
    metrics = runner.do_test(cfg, model)
    print("*" * 20)
    print(metrics)
    print("*" * 20)
    model.eval()
    return cfg,runner,model
```

**Comment by AhmedHessuin** [comment]
@wat3rBro  it call the  ```get_docs_dicts``` over and over 
```def get_data_ready_id():
    data_dir = '/media/machine1/992317707A58AEB3/EXPD2GO/d2go'

    for d in ["train_3"]:
        name="train"
        print("=============>","data_"+name)
        DatasetCatalog.register("data_" + name, lambda d=d: get_docs_dicts(data_dir+"/" + d))
```

**Comment by AhmedHessuin** [comment]
in terminal 
```
front
generating
back
generating
front_new
generating
back_new
generating
front
generating
back
generating
front_new
generating
```
till there is a leakage in my memory and train stops

**Comment by AhmedHessuin** [comment]
ok, after reading the script very good, i found out that you pass the data loading function to the model over and over while training
