### ISSUE TITLE
masks not detected properly

### ISSUE THREAD

**Issue by seekingdeep** [facebookresearch/d2go#12]
Hi there, 
the results seem weird, even after changing `MIN_SIZE_TEST`.
is this normal:

`Mask-RCNN-FBNetV3A`:
![2](https://user-images.githubusercontent.com/71519088/110211500-da2db980-7ea7-11eb-95f5-f1eeae39574c.jpg)

`mask_rcnn_fbnetv3a_dsmask_C4.yaml`:
![3](https://user-images.githubusercontent.com/71519088/110211536-fb8ea580-7ea7-11eb-8534-9acc7f12ea28.jpg)

`mask_rcnn_fbnetv3g_fpn.yaml`
![output1](https://user-images.githubusercontent.com/71519088/110211575-385a9c80-7ea8-11eb-98a1-fa464281fdb1.jpg)

**Comment by zhanghang1989** [comment]
I couldn't reproduce your problem. 
Did you use `trained=True` when loading the model from model_zoo?

This is my script:
```python
# Get the model
from d2go.model_zoo import model_zoo
model = model_zoo.get('mask_rcnn_fbnetv3a_C4.yaml', trained=True)
# Download the image 
import cv2
from matplotlib import pyplot as plt
!wget http://images.cocodataset.org/val2017/000000439715.jpg -q -O input.jpg
im = cv2.imread("./input.jpg")
plt.imshow(im)
# Make prediction
from d2go.utils.demo_predictor import DemoPredictor
predictor = DemoPredictor(model)
outputs = predictor(im)
# Visualize
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get("coco_2017_train"))
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
plt.imshow(out.get_image()[:, :, ::-1])
```

This is my output:
![image](https://user-images.githubusercontent.com/8041160/110217220-c6faf980-7e67-11eb-997f-9aa698971fd1.png)

**Comment by pape55** [comment]
A

**Comment by seekingdeep** [comment]
yes, i used `trained=True` as in `d2go_beginner.ipynb`
i am currently looking into the cause, meanwhile send the environment.yml 
```
conda env export > environment.yml
```

**Comment by seekingdeep** [comment]
alright, i found the solution.
it was caused by the version of the pytorch and numpy used.
using the latest `nightly` version of pytorch from conda , and the latest `stable` numpy have solved my issue.
