### ISSUE TITLE
i need someone to help me with training

### ISSUE THREAD

**Issue by AhmedHessuin** [facebookresearch/d2go#121]
can i display the training iteration ?
how does the model train and the optimizer?
can you show me what can make me run out of memory while training ?

**Comment by wat3rBro** [comment]
> can i display the training iteration ?

The iteration is shown in the stdout via Python's `logging` module. If you write your own command line tool, you probably need to setup the logger.

> how does the model train and the optimizer?

By default SGD is used, https://github.com/facebookresearch/detectron2/blob/main/detectron2/engine/train_loop.py#L267-L278 for the detail.

> can you show me what can make me run out of memory while training ?

Do you mean CPU or GPU memory? For CPU memory, it's linear to #GPUs per machine and size of datasets, larger number of data loader workers also increase the RAM usage. For GPU, it's basically related to how large the mode is, as well as the batch size.

**Comment by AhmedHessuin** [comment]
@wat3rBro  is it normal to run out of RAM after 20 000 iteration ?

**Comment by wat3rBro** [comment]
@AhmedHessuin One common case is running the evaluation (configured by `TEST.EVAL_PERIOD`) during training every N iterations, a test data loader is created temporarily that will take up some RAM.

**Comment by AhmedHessuin** [comment]
@wat3rBro  thank you.
