### ISSUE TITLE
i want some explaination about the training

### ISSUE THREAD

**Issue by AhmedHessuin** [facebookresearch/d2go#122]
when i register the training data, we make a function that take the input and the GT and put it in dictionary.
we use this step in the first phase (generating the training data).
my question is: 
"why do we call this function again while training over and over?"
didn't we get all the training data information in the first call of this function ?
why do we call it again ?
for me when i register the data the function is called over and over, making the training time huge (i train on over 100k  image)
the  part of script i am talking about 
```
def get_data_ready_id():
    data_dir = '/machine1/d2go'

    for d in ["train_3"]: #main train= train_3
        name="train"
        print("=============>","data_"+name)
        DatasetCatalog.register("data_" + name, lambda d=d: get_docs_dicts(data_dir+"/" + d,1))
```
the get_docs_dicts() function
it takes 2 h to load all data, if it load the data every time this is a high time consuming training

**Comment by wat3rBro** [comment]
Every time when you create a data loader, the `get_docs_dicts` (function registered in `DatasetCatalog.register`) will be called. For a normal training, the train data loader only needs to be created once, the test data loader will be created every time it runs the evaluation. From the naming of your code, seems it a train loader, so I suggest checking why the train loader is created multiple times.

https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html might also be helpful.

**Comment by AhmedHessuin** [comment]
@wat3rBro, well, i found out the evaluation call every 10000 is the one consume the memory and the time, i made it every 1000 000 and now it load for 1 time only, and saved time and training is smooth, thanks for your answer. it really helped me.
