### ISSUE TITLE
No module named 'torch.ao.quantization'

### ISSUE THREAD

**Issue by ajenez** [facebookresearch/d2go#128]
I currently have a custom version of the demo colab notebook, I had everything working around 1-2 months ago but just recently tried to run it and ran into an issue I hadn't seen before when I tried to start training. Below are all the installs and imports in my notebook and I'll also attach an image of the traceback. Thank you for your help.

!pip install 'git+https://github.com/facebookresearch/detectron2.git'
!pip install 'git+https://github.com/facebookresearch/mobile-vision.git'
!git clone https://github.com/facebookresearch/d2go
!pip install "/content/d2go"
!pip install 'git+https://github.com/facebookresearch/mobile-vision.git'
!pip install pyyaml==5.1
!pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.8/index.html

import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog

<img width="780" alt="Screen Shot 2021-10-21 at 1 33 46 PM" src="https://user-images.githubusercontent.com/76584875/138352659-6e3fcb3a-2f19-4aad-8330-1a6150a02688.png">

**Comment by pureloveljc** [comment]
pytorch 1.9  
changed 

" from torch.quantization "

**Comment by drkhan107** [comment]
@maheshs11 Can you please tell which 4 files do I need change (torch.ao to torch ) to fix this error.
