### ISSUE TITLE
ImportError: Cannot dynamically locate d2go.modeling.meta_arch.rcnn.D2RCNNInferenceWrapper.Preprocess

### ISSUE THREAD

**Issue by maheshs11** [facebookresearch/d2go#131]
![image](https://user-images.githubusercontent.com/7268915/139105718-c453c878-734f-463e-bf54-9ce9231452c1.png)
@zhanghang1989

**Comment by wat3rBro** [comment]
@maheshs11 sorry for the late reply, I think the issue is temporary, do you still have this issue?

**Comment by maheshs11** [comment]
> @maheshs11 sorry for the late reply, I think the issue is temporary, do you still have this issue?

no
