### ISSUE TITLE
Demo script fails with ImportError: cannot import name 'metanet_pb2' from 'caffe2.proto'

### ISSUE THREAD

**Issue by msalvaris** [facebookresearch/d2go#137]
## Instructions To Reproduce the 🐛 Bug:

What exact command you run:
python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input1.jpg --output output1.jpg

__Full logs__ or other relevant observations:
```
(d2go) mat@ada:~/repos/d2go/demo$ python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input1.jpg --output output1.jpg
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from d2go.model_zoo import model_zoo
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/d2go/model_zoo/model_zoo.py", line 7, in <module>
    from d2go.runner import create_runner
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/d2go/runner/__init__.py", line 10, in <module>
    from .default_runner import BaseRunner, Detectron2GoRunner, GeneralizedRCNNRunner
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/d2go/runner/default_runner.py", line 28, in <module>
    from d2go.export.d2_meta_arch import patch_d2_meta_arch
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/d2go/export/__init__.py", line 5, in <module>
    from . import torchscript  # noqa
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/d2go/export/torchscript.py", line 13, in <module>
    from detectron2.export.flatten import TracingAdapter, flatten_to_tuple
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/detectron2/export/__init__.py", line 3, in <module>
    from .api import *
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/detectron2/export/api.py", line 6, in <module>
    from caffe2.proto import caffe2_pb2
  File "/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/caffe2/proto/__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'metanet_pb2' from 'caffe2.proto' (/home/mat/anaconda3/envs/d2go/lib/python3.7/site-packages/caffe2/proto/__init__.py)
```

```
pytorch                   1.11.0.dev20211109 py3.7_cuda10.2_cudnn7.6.5_0    pytorch-nightly
pytorch-lightning         1.5.0                    pypi_0    pypi
```

Was unable to track down what the issue was. Tried installing stable PyTorch build and got segfault

**Comment by msalvaris** [comment]
Hmm, how did you install those versions in particular? I can't seem to get conda to do this

**Comment by savanovich** [comment]
I believe that the same possible with conda, but it was pip installation
`pip3 install --pre torch==1.11.0.dev20211001+cu113 torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`

**Comment by msalvaris** [comment]
That definitely seems to work. Although I did it for cuda 10.2
I did have to recreate the env a couple of time though to get it to work not sure what I did wrong the first time

**Comment by cloveropen** [comment]
savanovich is right!

**Comment by xiyinmsu** [comment]
> That definitely seems to work. Although I did it for cuda 10.2 I did have to recreate the env a couple of time though to get it to work not sure what I did wrong the first time

Hello, I am having the same issue and I use cuda10.2. Could you please share your command to install pytorch/torchvision on cuda10.2? Also, can you share command using conda if possible? thanks a lot in advance!

**Comment by LP308210365** [comment]
> hello, did you sovle it in cuda10.2 enviroment?, can you show the pytorch installation command?

**Comment by LP308210365** [comment]
@xiyinmsu

**Comment by nightheronry** [comment]
> savanovich
Hi guys, I tried to install torch==1.11.0.dev20211001+cu113, but this version seems to be deleted. Is there any solution ?
I also tried with torch-1.11.0.dev20211002+cu111, but it still had caffe2.proto importing issue.
Or, should I build pytorch with specific commit ?

**Comment by StrongCalvin** [comment]
Hi @nightheronry, 

I'm currently facing the same issue you had. Were you able to resolve this?

Thanks.

**Comment by maiiabocharova** [comment]
Also facing this issue. Please help

**Comment by swuerth** [comment]
I'm running into the same error.

**Comment by MoetezKd** [comment]
I'm facing the same issue! any solutions?

**Comment by gonggqing** [comment]
same question, sad...

**Comment by ridwan-salau** [comment]
I am also experiencing this problem.

My device is Mac M1. 
torch version: 1.13.0
torchaudio version: 0.13.0
torchvision version: 0.10.0
