### ISSUE TITLE
Run time crash while trying to get model from model zoo

### ISSUE THREAD

**Issue by arunniterate** [facebookresearch/d2go#138]
I have installed the requirements as mentioned in the beginner tutorial in  **Google Colab** and once I am running the following lines runtime is crashing:
from d2go.model_zoo import model_zoo
model = model_zoo.get('faster_rcnn_fbnetv3a_C4.yaml', trained=True)
Any ideas ?

**Comment by cloveropen** [comment]
plz see #141
