### ISSUE TITLE
Error: No module named 'fcntl' - cannot train d2go on windows

### ISSUE THREAD

**Issue by shank-imironman** [facebookresearch/d2go#140]
I followed installation instruction from readme. It showed installation was successful.
When I try to train model on windows, it gives error "Error: No module named 'fcntl' ". 
As fcntl is not available for windows which makes d2go unusable on windows.
How to work around this ?

![error](https://user-images.githubusercontent.com/21685831/142703347-9d25fdb3-28a4-415b-8a9a-ffae6f85aeaa.png)

PS :- I am able to train and inference detectron2 models, issue only comes with d2go.

**Comment by wat3rBro** [comment]
We don't test on windows, but https://github.com/facebookresearch/mobile-vision/pull/57 should fix it.
