### ISSUE TITLE
 ModuleNotFoundError: No module named 'torch.ao.quantization.quantize_fx'

### ISSUE THREAD

**Issue by TannerGilbert** [facebookresearch/d2go#141]
## Instructions To Reproduce the 🐛 Bug:
1. Run [Jupyter Notebook](https://github.com/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2/blob/master/D2Go/D2GO_Introduction.ipynb) in Google Colab.

## Expected behavior:

D2Go should work with PyTorch version `1.10.0+cu111`.

Possible fix:

Change:
```
from torch.ao.quantization.quantize_fx import prepare_fx, prepare_qat_fx, convert_fx
```

to 

```
from torch.quantization.quantize_fx import prepare_fx, prepare_qat_fx, convert_fx
```

**Comment by cloveropen** [comment]
in Jupyter Notebook,open the  /usr/local/lib/python3.7/dist-packages/d2go/modeling/meta_arch/rcnn.py and modify as 
 from torch.quantization.quantize_fx import prepare_fx, prepare_qat_fx, convert_fx

**Comment by TannerGilbert** [comment]
Related to #136

**Comment by TannerGilbert** [comment]
Was able to temporarily fix the issue using the following code:

```
with open('/usr/local/lib/python3.7/dist-packages/d2go/modeling/meta_arch/rcnn.py', 'r') as f:
  rcnn_py = f.read()

with open('/usr/local/lib/python3.7/dist-packages/d2go/modeling/meta_arch/rcnn.py', 'w') as f:
  rcnn_py = rcnn_py.replace('torch.ao.quantization', 'torch.quantization')
  f.write(rcnn_py)
```

The fix discussed in #136 should also work.

**Comment by mythri1996** [comment]
Can you please suggest me to resolve dependency issue and if i want execute code in google colab, required cuda and pytorch version?
 Already tried with 1.10.0+cu111 ,  cuda 10.2  it is not working, getting error like  ModuleNotFoundError: No module named 'torch.ao' and some other issues

**Comment by wat3rBro** [comment]
@mythri1996 `torch.ao` was added in 1.10, but maybe you still need a newer version. For D2Go we recommend using the latest pytorch-nightly.

**Comment by mythri1996** [comment]
@wat3rBro thank you, previous issue resolved

How to install d2go,mobile-vision in google colab ?

**Comment by wat3rBro** [comment]
@mythri1996  I haven't tried d2go/mobile-vision + google colab, but assume you can install them using pip following https://github.com/facebookresearch/d2go#installation

**Comment by dipu0** [comment]
> @mythri1996 I haven't tried d2go/mobile-vision + google colab, but assume you can install them using pip following https://github.com/facebookresearch/d2go#installation

each time i run train cell colab crashed! 
https://stackoverflow.com/questions/75666142/colab-sessions-crash-every-time-i-run-this-code-from-d2go

**Comment by pgzmnk** [comment]
```
File [~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:5](https://vscode-remote+ssh-002dremote-002bp3-002e2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/geomlcv/docs/notebooks/~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:5)
      [3](https://vscode-remote+ssh-002dremote-002bp3-002e2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/geomlcv/docs/notebooks/~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:3) from torch import Tensor
      [4](https://vscode-remote+ssh-002dremote-002bp3-002e2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/geomlcv/docs/notebooks/~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:4) from torch import nn
----> [5](https://vscode-remote+ssh-002dremote-002bp3-002e2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/geomlcv/docs/notebooks/~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:5) from torch.ao.quantization import QuantStub, DeQuantStub
      [6](https://vscode-remote+ssh-002dremote-002bp3-002e2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/geomlcv/docs/notebooks/~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:6) from torchvision.models.mobilenetv2 import InvertedResidual, MobileNetV2, model_urls
      [8](https://vscode-remote+ssh-002dremote-002bp3-002e2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/geomlcv/docs/notebooks/~/.venv/lib64/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py:8) from ..._internally_replaced_utils import load_state_dict_from_url

ModuleNotFoundError: No module named 'torch.ao.quantization'
```
