### ISSUE TITLE
May I ask what's the mAP trained on detr with fbv3 backbone? (not vit version)

### ISSUE THREAD

**Issue by luohao123** [facebookresearch/d2go#148]
May I ask what's the mAP trained on detr with fbv3 backbone? (not vit version)

I tried without pretrained weights, but mAP inrease very slow.

**Comment by wat3rBro** [comment]
Please refer to the `Pretrained Models` in https://github.com/facebookresearch/d2go/tree/main/projects_oss/detr#pretrained-models.

**Comment by luohao123** [comment]
@wat3rBro OK, 27.3 relatively low, same value as I trained.

**Comment by zhanghang1989** [comment]
Lower result than ResNet backbone is expected. The FBNetV3 is a set of small models.
