### ISSUE TITLE
RuntimeError: mask_rcnn_fbnetv3g_fpn.yaml not available in Model Zoo!

### ISSUE THREAD

**Issue by ys31jp** [facebookresearch/d2go#162]
I have installed according to this installation
![image](https://user-images.githubusercontent.com/83806490/148800533-e80ccd9a-3e84-4d79-850e-312c117e4b97.png)

but then when I run the d2go_beginner and demo.py
it will have this RuntimeError
![image](https://user-images.githubusercontent.com/83806490/148800389-43825577-0b0b-4365-b6f1-3b687e7af70f.png)

**Comment by cloveropen** [comment]
please copy d2go\configs\* to e:\anaconda3\envs\d2go_22\lib\site-packages\d2go

**Comment by wat3rBro** [comment]
Hi, I updated the config file location in https://github.com/facebookresearch/d2go/pull/152, it changes the `setup.py` so you might need to re-install the d2go.

**Comment by ys31jp** [comment]
Hi, the issues solved, thank you.

**Comment by ross-Hr** [comment]
So hard for beginners!

Your need to create soft link to your detectron2 install directory, eg:

```
ln -s  path_to_my_project/configs/COCO/common/    path_to_detectron2_install_directory/detectron2/detectron2/model_zoo/configs/
```
