### ISSUE TITLE
RuntimeError: keypoint_rcnn_fbnetv3a_dsmask_C4.yaml not available in Model Zoo!

### ISSUE THREAD

**Issue by ashutoshsoni891** [facebookresearch/d2go#20]
Hi!

Here is the google colab `https://colab.research.google.com/drive/1YYsH0ofAghS5W6PcZ5tBizCnLsJumuIe?usp=sharing` . When I am trying to load the Zoo model 

```
from d2go.model_zoo import model_zoo
cfg = model_zoo.get('keypoint_rcnn_fbnetv3a_dsmask_C4.yaml')
```

but it says : **RuntimeError: keypoint_rcnn_fbnetv3a_dsmask_C4.yaml not available in Model Zoo!**
I checked the model_zoo.py file and found that the above model exists. Could you please help me out

**Comment by TannerGilbert** [comment]
Your installation doesn't work. You can use:
```python
!pip install 'git+https://github.com/facebookresearch/detectron2.git'
!pip install 'git+https://github.com/facebookresearch/mobile-vision.git'

!git clone https://github.com/facebookresearch/d2go
%cd d2go
!pip install .
%cd /content
```

**Comment by zhanghang1989** [comment]
For collab, you may try this one:
https://colab.research.google.com/gist/zhanghang1989/4ab8cbecbd05e1cc8fca8fd4dbaf8841/d2go_beginner.ipynb

**Comment by ashutoshsoni891** [comment]
thanks @zhanghang1989 @TannerGilbert for your help guys . I am closing the issue

**Comment by VladAndronik** [comment]
@ashutoshsoni891 have you been able to solve the issue? I have the same problem following the installation tutorial from README and I also tried the one in colab for my local machine, but still have the same problem.

**Comment by vishnukarthik-1994** [comment]
@VladAndronik  and @ashutoshsoni891 , were you able to resolve this issue? When to try to create the d2go model by following the steps here: https://github.com/pytorch/android-demo-app/tree/master/D2Go, I run into this issue.
