### ISSUE TITLE
KeyError: 'Non-existent config key: EXPORT_CAFFE2'

### ISSUE THREAD

**Issue by ashutoshsoni891** [facebookresearch/d2go#23]
Hi !
I am trying to train custom keypoint model on D2go . While setting config file parameter `cfg.merge_from_file(model_zoo.get_config_file("keypoint_rcnn_fbnetv3a_dsmask_C4.yaml"))
`
I am getting error : **KeyError: 'Non-existent config key: EXPORT_CAFFE2'** .Seems like this is a bug

**Comment by zhanghang1989** [comment]
Could you comment out these two lines:
https://github.com/facebookresearch/d2go/blob/f23248c08db11c94477d150ba62db5dc64e643ec/configs/keypoint_rcnn_fbnetv3a_dsmask_C4.yaml#L71-L72
