### ISSUE TITLE
Unable to install d2go although pytorch, torhcvison , detectro2 , mobile vision all are installed as per steps in d2go git documenation

### ISSUE THREAD

**Issue by Abhishek11Git** [facebookresearch/d2go#247]
fatal : reference is not a tree

unable to checkout 'acvJHFBJEFBEK.JFnlkew/vwnk,vbkwejvnw.' in submodule path '_notebooks'

git submodule update --init --recursive -q did not run sucessfully.

**Comment by wat3rBro** [comment]
Seems duplicated with https://github.com/facebookresearch/d2go/issues/246.
