### ISSUE TITLE
need android demo

### ISSUE THREAD

**Issue by siyangbing** [facebookresearch/d2go#30]
---

## 🚀 Feature
A clear and concise description of the feature proposal.

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

**Comment by TannerGilbert** [comment]
There is already a [android demo](https://github.com/pytorch/android-demo-app/tree/master/D2Go).

**Comment by kmistry-wx** [comment]
Will there also be one for iOS soon?

**Comment by jeffxtang** [comment]
> Will there also be one for iOS soon?

https://github.com/pytorch/ios-demo-app/tree/master/D2Go
