### ISSUE TITLE
ImportError: cannot import name 'get_fqn_to_example_inputs' from 'torch.ao.quantization.utils' (/usr/local/lib/python3.7/dist-packages/torch/ao/quantization/utils.py)

### ISSUE THREAD

**Issue by nikitha-debug** [facebookresearch/d2go#337]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>
```
2. What exact command you run:
3. __Full logs__ or other relevant observations:
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

**Comment by bryantwilliam** [comment]
Are you still getting this error after re-installing pytorch-nightly?
Same error: #360 https://github.com/facebookresearch/d2go/issues/360

**Comment by pinecho** [comment]
@bryantwilliam I solved the problem after I re-install the pytorch-nightly.
1. Find the install command at [pytorch.org](https://pytorch.org/get-started/locally/) .
2. Run the install command.
3. Check the version of torch and torchvision are the latest and compatiable in [torch-torchvision matrix](https://github.com/pytorch/vision#installation).
