### ISSUE TITLE
Error importing zoo model on Colab

### ISSUE THREAD

**Issue by Fatichti** [facebookresearch/d2go#360]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
python -m pip install 'git+https://github.com/facebookresearch/mobile-vision.git'
python -m pip install 'git+https://github.com/facebookresearch/d2go.git'
```
2. What exact command you run:

`from d2go.model_zoo import model_zoo`
or
`import 2dgo`

3. __Full logs__ or other relevant observations:
```
ImportError: cannot import name 'get_fqn_to_example_inputs' from 'torch.ao.quantization.utils' (/usr/local/lib/python3.7/dist-packages/torch/ao/quantization/utils.py)
```
5. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.

## Expected behavior:

`That it is possible to import the zoo model (and d2go in general) in google collab`

**Comment by bryantwilliam** [comment]
I'm also getting this error:
`$ python demo.py --config-file keypoint_rcnn_fbnetv3a_dsmask_C4.yaml --input input1.jpg --output output1.jpg
C:\Python38\lib\site-packages\caffe2\__init__.py:5: UserWarning: Caffe2 support is not fully enabled in this PyTorch build. Please enable Caffe2 by building PyTorch from source with `BUILD_CAFFE2=1` flag.
  warnings.warn("Caffe2 support is not fully enabled in this PyTorch build. "
C:\Python38\lib\site-packages\caffe2\proto\__init__.py:17: UserWarning: Caffe2 support is not enabled in this PyTorch build. Please enable Caffe2 by building PyTorch from source with `BUILD_CAFFE2=1` flag.
  warnings.warn('Caffe2 support is not enabled in this PyTorch build. '
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from d2go.model_zoo import model_zoo
  File "C:\Python38\lib\site-packages\d2go\__init__.py", line 7, in <module>
    from d2go import initializer, optimizer  # NOQA
  File "C:\Python38\lib\site-packages\d2go\initializer.py", line 43, in <module>
    initialize_all()
  File "C:\Python38\lib\site-packages\d2go\initializer.py", line 38, in initialize_all
    _register()
  File "C:\Python38\lib\site-packages\d2go\initializer.py", line 28, in _register
    from d2go.modeling.backbone import fbnet_v2  # noqa
  File "C:\Python38\lib\site-packages\d2go\modeling\__init__.py", line 6, in <module>
    from . import backbone, meta_arch, modeldef  # noqa  # noqa  # noqa
  File "C:\Python38\lib\site-packages\d2go\modeling\meta_arch\__init__.py", line 6, in <module>
    from . import fcos, panoptic_fpn, rcnn, retinanet, semantic_seg  # noqa
  File "C:\Python38\lib\site-packages\d2go\modeling\meta_arch\rcnn.py", line 37, in <module>
    from torch.ao.quantization.utils import get_fqn_to_example_inputs
ImportError: cannot import name 'get_fqn_to_example_inputs' from 'torch.ao.quantization.utils' (C:\Python38\lib\site-packages\torch\ao\quantization\utils.py)
`

**Comment by wat3rBro** [comment]
@bryantwilliam `get_fqn_to_example_inputs` should be available in pytorch-nightly, do you still have the issue?

**Comment by wat3rBro** [comment]
@pinecho hmmm, I'm not sure why. Could you double check your local pytorch-nightly is up-to-date, maybe also try the pre-compiled one.

**Comment by pinecho** [comment]
@wat3rBro Thanks, I ran the demo successfully. 
But there was a problem with the demo [d2go_beginner.ipynb](https://github.com/facebookresearch/d2go/blob/e93de5d2b82dcc1a575b3d4f2d31c8708cac13ed/demo/d2go_beginner.ipynb)
the code:
- `from d2go.export.d2_meta_arch import patch_d2_meta_arch` 
- `patch_d2_meta_arch()` 

in section **Export to Int8 Model** may not needed anymore, because you remove it on [wat3rBro:export-D37246483](https://github.com/facebookresearch/d2go/pull/305)

**Comment by wat3rBro** [comment]
@pinecho exactly, gonna update the ipynb.
