### ISSUE TITLE
Error while importing the model_zoo

### ISSUE THREAD

**Issue by Fatichti** [facebookresearch/d2go#361]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```bash
$ uname -a 
Linux user 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ conda --version 
4.13.0
$ nvcc --version
Build cuda_11.6.r11.6/compiler.31057947_0
$ python -V
Python 3.9.12
$ python -c "import torch; print(torch.__version__)"
1.13.0a0+git4b3f1bd
```

2. What exact command you run:  
  
✅Installed PyTorch [from source](https://github.com/pytorch/pytorch)
```bash
$ cd pytorch
$ python setup.py install
```
✅Pytorch with CUDA and CAFFE2 successfully compiled
```python
from d2go.model_zoo import model_zoo
```
❌Error while importing the model_zoo  

3. __Full logs__ or other relevant observations:
```bash
libtorch_cuda_cpp.so: undefined symbol
This caffe2 python run failed to load cuda module
```
Details :
![image](https://user-images.githubusercontent.com/74354655/185553434-12b546b6-4396-4aec-a4e3-4f317b846ca0.png)

## Expected behavior:
Successful import of the model_zoo module

**Comment by wat3rBro** [comment]
close the issue since there should be no caffe2 related code at import time now
