### ISSUE TITLE
Error while exporting to INT8

### ISSUE THREAD

**Issue by AmeenAli** [facebookresearch/d2go#363]
Hello

I am using the following detectron2 model :

MODEL: 
    META_ARCHITECTURE: "GeneralizedRCNN"
    BACKBONE:
        NAME: "build_resnet_fpn_backbone"
    RESNETS:
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]
        DEPTH: 101
    FPN:
        IN_FEATURES: ["res2", "res3", "res4", "res5"]
    ANCHOR_GENERATOR:
        SIZES: [[32], [64], [128], [256], [512]] # One size for each in feature map
        ASPECT_RATIOS: [[0.5, 1.0, 2.0]] # Three aspect ratios (same for all in feature maps)
    RPN:
        IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
        PRE_NMS_TOPK_TRAIN: 2000 # Per FPN level
        PRE_NMS_TOPK_TEST: 1000 # Per FPN level
        POST_NMS_TOPK_TRAIN: 1000
        POST_NMS_TOPK_TEST: 1000

However, once I try to export it to INT8 by following the demo notebook, I get the following error: 
`NotImplementedError: Could not run 'quantized::conv2d_prepack' with arguments from the 'QuantizedCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'quantized::conv2d_prepack' is only available for these backends: [QuantizedCPU, BackendSelect, Python, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, Tracer, AutocastCPU, AutocastCUDA, Batched, VmapMode, PythonTLSSnapshot].`

Any idea what's wrong?

Thanks,

**Comment by wat3rBro** [comment]
@AmeenAli the quantization for original Detectron2 model is not fully supported.
