### ISSUE TITLE
how to set mutil gpu train?

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/d2go#41]
---

## 🚀 Feature
A clear and concise description of the feature proposal.

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

**Comment by zhanghang1989** [comment]
You may set `--num-processes` to control number of gpus in https://github.com/facebookresearch/d2go/blob/master/tools/train_net.py.
see options at https://github.com/facebookresearch/d2go/blob/b2b8e21681d919c101bf0341d5cf2bb0f21ae58c/d2go/setup.py#L68
