### ISSUE TITLE
'allow_override'

### ISSUE THREAD

**Issue by petoor** [facebookresearch/d2go#48]
Importing get_config results in:

```
from d2go.model_zoo.model_zoo import get_config
TypeError: __init__() got an unexpected keyword argument 'allow_override'
```
Promblem can be solved by removing allow_override in https://github.com/facebookresearch/d2go/blob/master/d2go/export/api.py#L208

`ModelExportMethodRegistry = Registry("ModelExportMethod", allow_override=True)`

However, I do not know if it is safe to remove the allow_override argument.

**Comment by zhanghang1989** [comment]
Thanks for the feedback. It is because the mobile_cv isn't updated yet. @wat3rBro is looking into it.

**Comment by wat3rBro** [comment]
@petoor should be solved by https://github.com/facebookresearch/mobile-vision/pull/44

**Comment by petoor** [comment]
Yes, it is working.

Cheers.
