### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.ao.pruning'

### ISSUE THREAD

**Issue by HenryZ94264** [facebookresearch/d2go#488]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<**I didn't make any changes to the code.**>
```
2. What exact command you run:
`python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input input1.jpg --output output1.jpg
`
3. __Full logs__ or other relevant observations:
```
<Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from d2go.model_zoo import model_zoo
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/model_zoo/model_zoo.py", line 7, in <module>
    from d2go.runner import create_runner
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/runner/__init__.py", line 9, in <module>
    from .default_runner import BaseRunner, Detectron2GoRunner, GeneralizedRCNNRunner
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/runner/default_runner.py", line 14, in <module>
    from d2go.checkpoint import FSDPCheckpointer, is_distributed_checkpoint
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/checkpoint/__init__.py", line 2, in <module>
    from .fsdp_checkpoint import FSDPCheckpointer
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/checkpoint/fsdp_checkpoint.py", line 9, in <module>
    from d2go.trainer.fsdp import FSDPWrapper
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/trainer/fsdp.py", line 16, in <module>
    from torch.ao.pruning import fqn_to_module
ModuleNotFoundError: No module named 'torch.ao.pruning'>
```
4. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.
The pytorch version is 1.13.1+cu116

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

**Comment by wat3rBro** [comment]
The `torch.ao.pruning` module is added in PyTorch 2.0, anyway the best way to avoid such issue is probably using the PyTorch nightly build. I don't think you'll need to use `fqn_to_module` in your code, so comment that line out can be a workaround.

**Comment by HenryZ94264** [comment]
> The `torch.ao.pruning` module is added in PyTorch 2.0, anyway the best way to avoid such issue is probably using the PyTorch nightly build. I don't think you'll need to use `fqn_to_module` in your code, so comment that line out can be a workaround.

The code works after I comment this line.
But I met another problem of import model_ema
when I add this line of code
`from d2go.modeling import kmeans_anchors, model_ema`

File "/data0/file_server/zh/exp/ifsod/sylph/runner/meta_fcos_runner.py", line 26, in <module>
    from d2go.modeling import kmeans_anchors, model_ema
ImportError: cannot import name 'model_ema' from 'd2go.modeling' (/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/__init__.py)

Should I change this to `from d2go.modeling import ema`？

**Comment by wat3rBro** [comment]
Yes we renamed the `model_ema.py` to `ema.py`.

**Comment by HenryZ94264** [comment]
> Yes we renamed the `model_ema.py` to `ema.py`.

Thanks a lot! :smiley:
