### ISSUE TITLE
How to register detector to D2Go's META_ARCH_REGISTRY.

### ISSUE THREAD

**Issue by HenryZ94264** [facebookresearch/d2go#490]
The detector have a decorator like this
`
@META_ARCH_REGISTRY.register() 
`
`
class MetaOneStageDetector(MetaProposalNetwork):
`

I think this decorator is to register the MetaOneStageDetector to D2.

And when I run the code, it raise this error：
KeyError: "Can't find 'MetaOneStageDetector' in D2Go's META_ARCH_REGISTRY, although it is in D2's META_ARCH_REGISTRY, now D2Go uses its own registry, please register it in D2Go's META_ARCH_REGISTRY."

How to register detector to D2Go's META_ARCH_REGISTRY?
Is there any documentation or instruction to follow？

**Comment by wat3rBro** [comment]
As the error message says, please use `from d2go.registry.builtin import META_ARCH_REGISTRY` instead of `detectron2.modeling import META_ARCH_REGISTRY`.
