### ISSUE TITLE
Mask rcnn trained with QAT is giving false negative 1.0 when trained with Custom datasets.

### ISSUE THREAD

**Issue by labs10** [facebookresearch/d2go#504]
I am training a custom dataset on d2go mask rcnn with QAT but I am continuously getting a false negative 1.0 after 1000 interation it is when the model starts to quantize. 

Here is the configuration I used for training. 

```
    runner = GeneralizedRCNNRunner()
    cfg = runner.get_default_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("mask_rcnn_fbnetv3g_fpn.yaml"))
    #USE QUANTIZATION AWARE TRAINING
    cfg.QUANTIZATION.QAT.ENABLED = True
    cfg.QUANTIZATION.QAT.BATCH_SIZE_FACTOR = 1.0
    cfg.QUANTIZATION.BACKEND = "qnnpack"
    cfg.QUANTIZATION.QAT.FAKE_QUANT_METHOD = "default"
    cfg.QUANTIZATION.QAT.START_ITER = 1000
    cfg.QUANTIZATION.QAT.ENABLE_OBSERVER_ITER = 1000
    cfg.QUANTIZATION.QAT.ENABLE_LEARNABLE_OBSERVER_ITER = 1100
    cfg.QUANTIZATION.QAT.DISABLE_OBSERVER_ITER = 1100 + 100
    cfg.QUANTIZATION.QAT.FREEZE_BN_ITER = 1000
    cfg.MODEL_EMA.ENABLED = False
    cfg.DATASETS.TRAIN = ("train",)
```
 

Any help and feedback will be appreciated.

**Comment by wat3rBro** [comment]
`model_zoo.get_config_file("mask_rcnn_fbnetv3g_fpn.yaml")` will return a untrained model, i.e. the `cfg.MODEL.WEIGHTS` is empty, so you're performing QAT from scratch, in such case 1000 iterations are not enough.

**Comment by labs12** [comment]
@wat3rBro , thanks for the comment. I've solved the issue by adding `cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("mask_rcnn_fbnetv3a_C4.yaml")` to the configurations. Now, the model is working fine.
