### ISSUE TITLE
how can i train the model by pascal data format?

### ISSUE THREAD

**Issue by Yaoxingtian** [facebookresearch/d2go#84]
hi, thanks for your open source.
i wanna train my own data and it's pascal data format , could you show example about how to use pascal datasets?

thanks a lot!

**Comment by wat3rBro** [comment]
Similar to https://github.com/facebookresearch/d2go/issues/85, please follow the way that Detectron2 adds pascal VOC (eg. https://github.com/facebookresearch/detectron2/issues/991)
