### ISSUE TITLE
ImportError: Cannot dynamically locate d2go.utils.export_utils.D2RCNNTracingWrapper.RunFunc

### ISSUE THREAD

**Issue by Parth38** [facebookresearch/d2go#89]
I am training a custom model. After post-training quantization , exporting to int8 model I went on to create a predictor using the exported int8 model.
Apart from dataset changes I haven't made any changes to the code in d2go_beginner.ipynb

`from mobile_cv.predictor.api import create_predictor
model = create_predictor(predictor_path)`
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-28-388e768b3466> in <module>()
      1 from mobile_cv.predictor.api import create_predictor
----> 2 model = create_predictor(predictor_path)

3 frames
/usr/local/lib/python3.7/dist-packages/mobile_cv/common/misc/py.py in dynamic_import(obj_full_name)
     43     ret = pydoc.locate(obj_full_name)
     44     if ret is None:
---> 45         raise ImportError("Cannot dynamically locate {}".format(obj_full_name))
     46     return ret
     47 

ImportError: Cannot dynamically locate d2go.utils.export_utils.D2RCNNTracingWrapper.RunFunc`

**Comment by wat3rBro** [comment]
@Parth38 can you try https://github.com/facebookresearch/mobile-vision/pull/52/ and see if it works?

**Comment by wat3rBro** [comment]
Close now, please re-open if the problem still exists.
