### ISSUE TITLE
ModuleNotFoundError: No module named 'd2go.tools'

### ISSUE THREAD

**Issue by REXIMMORTAL** [facebookresearch/d2go#9]
Hi, thanks for your great job. I  installed the environment as ReadMe said. No erros during setting up environment. But when I executed the example, I came across an ERROR:
```
~/d2go$ d2go.train_net --config-file ./configs/faster_rcnn_fbnetv3a_C4.yaml
Traceback (most recent call last):
  File "/home/lbc/anaconda3/envs/d2go/bin/d2go.train_net", line 5, in <module>
    from d2go.tools.train_net import cli
ModuleNotFoundError: No module named 'd2go.tools'
```
But in python interpreter environment, it's fine to import d2go.tools in current directory. It will report the same error in the up-level dir.
```
~/d2go$ python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from d2go.tools.train_net import cli
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

>>>

```

**Comment by zhanghang1989** [comment]
I think that's because you are inside the repo folder and it tries to import from local directory. You may run this command in tools directory.

**Comment by REXIMMORTAL** [comment]
Thanks for your reply. I found other submodules fine, and I checked the submodule dir, and I found the reason is that an empty `__init__.py` file is missing in the `tests/` dir. After adding it, everything goes fine.

**Comment by mathpopo** [comment]
@zhanghang1989 
also happpen, i update to latest.
(base) chenxin@Nitro-AN515:~/Downloads/d2go$ conda activate detectron2
(detectron2) chenxin@Nitro-AN515:~/Downloads/d2go$ d2go.train_net --config-file ./configs/faster_rcnn_fbnetv3a_C4.yaml
Traceback (most recent call last):
  File "/home/chenxin/anaconda/envs/detectron2/bin/d2go.train_net", line 5, in <module>
    from d2go.tools.train_net import cli
ModuleNotFoundError: No module named 'd2go.tools'

**Comment by zhanghang1989** [comment]
I think it may be because you're inside the repo. Could you try:
```bash
cd configs/
d2go.train_net --config-file faster_rcnn_fbnetv3a_C4.yaml
```

**Comment by mathpopo** [comment]
@zhanghang1989 very thanks, if want to set 8GPU to work ,how can i set?like detectron?

**Comment by zhanghang1989** [comment]
I believe it should use all the available gpus. What's the behavior on your side?
