### ISSUE TITLE
ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so

### ISSUE THREAD

**Issue by Parth38** [facebookresearch/d2go#95]
I am working on Google colab. Need to reinstall for every new  experiment. It was working fine till yesterday (after fixing final from typing error). New error:
ImportError                               Traceback (most recent call last)

<ipython-input-2-ffdbfe040df2> in <module>()
----> 1 from d2go.model_zoo import model_zoo
      2 model = model_zoo.get('faster_rcnn_fbnetv3a_C4.yaml', trained=True)

12 frames

/usr/local/lib/python3.7/dist-packages/torchtext/vocab.py in <module>()
     11 from typing import Dict, List, Optional, Iterable
     12 from collections import Counter, OrderedDict
---> 13 from torchtext._torchtext import (
     14     Vocab as VocabPybind,
     15 )

ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZN3c106ivalue6Future15extractDataPtrsERKNS_6IValueE

**Comment by maheshs11** [comment]
install pytorch 1.9

**Comment by Parth38** [comment]
Tried it gving error : `from torchtext._torchtext import RegexTokenizer as RegexTokenizerPybind`

**Comment by zhanghang1989** [comment]
Could you try:
`!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'` as mentioned in https://github.com/facebookresearch/d2go/issues/92
